### PR TITLE
feat: use logging to replace print #117

### PR DESCRIPTION
**Pull request by lgeo3**
First draft to use logging to replace print (issue #117)

### CODE REVIEW

**Comment by tgrandje** [comment]
Hello. Two quick questions about this PR : 

- should we expressly set the logging level in the module ? As you systematically substitued `logging.info` to each `print`, I think it undermines the whole purpose of it (which was about pynsee beeing too verbose) ?

- should'nt we switch logging.info to logging.warning / logging.error in some cases ? I agree pynsee is too verbose, but some message should be displayed in most cases (for instance `"f"File not found on insee.fr:\n{url}" "Please open an issue on:\nhttps://github.com/InseeFrLab/pynsee"`).

By the way, I'm thinking it may be a good opportunity to rethink some "multilines" comments in "one-liners". It would keep the logs concise (for instance to continue with the previous example, something like `"f"File not found on insee.fr:\n{url}. Please open an issue on: https://github.com/InseeFrLab/pynsee"`) and easily readable.

**Comment by tfardet** [comment]
I agree with @tgrandje : "info" should only be used for things that are part of the normal workflow. Anything unusual should at least be "warning" and things related to files not found, data used instead of another, or anything saying people should contact the maintainer or raise an issue here should be "critical" IMO.

**Comment by tgrandje** [comment]
@lgeo3 I just did a PR on your own PR to try to set the levels in accordance with the current discussion (feel free to change it!) . 

_This is my firt PR on PR, I hope I've been doing this according to the rule : if not, let me know and I'll try to do a direct PR from my repo._

**Comment by hadrilec** [comment]
I would like to make a new release in the coming days, @lgeo3 could you please review the PR on your fork and let me know if the code is ready to be published or if further fine tuning is needed

**Comment by tgrandje** [comment]
@hadrilec @tfardet I just moved the PR to the main repo (through https://github.com/InseeFrLab/pynsee/pull/135)

**Comment by tfardet** [comment]
Closing due to inactivity in favor of #135

**Pull request closed without merging**
