### PR TITLE
Unify os.environ['https_proxy'] calls through whole package

### PR DESCRIPTION
**Pull request by tgrandje**
Sometimes https_proxy where constructed using os.environ['http_proxy'], sometimes using os.environ['https_proxy'].
This PR unify the variable used (ie http**s**_proxy)

### CODE REVIEW

**Comment by hadrilec** [comment]
@tgrandje, thanks a lot for all your contributions!
I made some modifications on top of it to ensure consistency in the namespace.
I would like to push  on [tgrandje-patch-https_proxy](https://github.com/tgrandje/pynsee/tree/tgrandje-patch-https_proxy) branch on [tgrandje/pynsee](https://github.com/tgrandje/pynsee) to update this PR.
Could you please give me this right?
Otherwise, your commits and my follow-up commits are on this branch [tgrandje-patch-https_proxy](https://github.com/InseeFrLab/pynsee/commits/tgrandje-patch-https_proxy).

**Comment by tgrandje** [comment]
@hadrilec sure ! I might have done it, but I'm note 100% sure (doing this from m'y phone + not a specialist of github...). Can you check if this works ?

**Comment by hadrilec** [comment]
Thanks a lot, I have managed to push to your repo.

**Comment by tgrandje** [comment]
@hadrilec Well, for someone who didn't have much time, you certainly had a busy weekend ! I'm not sure what to read of unsuccesfull tests, but let me know if there is anything I can do to help.

**Pull request merged**
