### PR TITLE
Test Python 3.8/3.11 + backup multiprocessing to get geodata

### LINKED ISSUE #172: Test against relevant python versions
I'd propose to stop testing against python 3.7, as it already reached [end of life](https://endoflife.date/python) and start using 3.11 instead.

I also wonder whether it is necessary to test against all intermediate versions and whether oldest and newest alone would not be sufficient (especially given how long the tests take to run). No strong opinion, though, just wondering whether it's worth it.

### PR DESCRIPTION
**Pull request by tfardet**
Fixes #172 and #175 

@hadrilec are these the main changes you had included in #162? If not, feel free to include whatever is missing.

### CODE REVIEW

**Comment by tfardet** [comment]
@hadrilec Well, it seems we now know where the 4h-long tests come from ^^"

**Comment by tfardet** [comment]
@hadrilec I won't have time to look at this for the moment, so if you can have a look, it would be worth checking what makes the multiprocessing fail.
I also wonder whether this is the best way to handle this and if we shouldn't rather move to something like [this](https://stackoverflow.com/a/57129241/5962321), might be just as fast (faster?) and more reliable.

**Comment by hadrilec** [comment]
Thanks for the link, I will have a look. I agree async should be the way to go.

**Comment by hadrilec** [comment]
I did a mistake by pushing commits from the other PR, my bad, I will clean this up

**Comment by tfardet** [comment]
@hadrilec do you know when you'd have time to finish this part?

**Pull request closed without merging**
