### PR TITLE
Move to parquet and platformdirs

### PR DESCRIPTION
**Pull request by tfardet**
Use parquet instead of pickle to store datasets (around 100 times faster), should be supported since pandas 0.21 and we require 0.24.

Move to platformdirs for cache folder, etc, as appdirs is unmaintained.

### CODE REVIEW

**Comment by tfardet** [comment]
Apparently I need to add pyarrow as a dependency for parquet to run (I thought it was installed by default with pandas now, but apparently not), let's see if it runs fine this time.
@hadrilec  I hope the additional dependency is OK with you, I really think parquet is the way forward in terms of storing data (both to save space and fast IO).

**Comment by tfardet** [comment]
@hadrilec you can have a look, tests are passing now that SIRENE is fixed

**Comment by tfardet** [comment]
@hadrilec let me know if you need further info to validate that PR

**Comment by hadrilec** [comment]
@tfardet thanks a lot, do you think it would be possible to move pyarrow to the optional packages? meaning to the extras_require list in setup.py file. In doing so, we would allow the users to use pyarrow if they want and it would not add a "hard" dependency on pyarrow. if this too much trouble, let me know

**Comment by tfardet** [comment]
> do you think it would be possible to move pyarrow to the optional packages?

This is theoretically possible but I would strongly advise against it: this would require two different codes to handle file for people with and without pyarrow and making pyarrow non-default would mean that most people would not get the benefits from the new parquet format...

Is there a specific issue with pyarrow that you are aware of?
As far as I know they provide wheels so installation should never be an issue...

**Pull request merged**
